Pid:
  PURE:
    gym_id: Pid-v0
    num_envs: 16
    total_timesteps: 150000
  FRAMESKIP:
    gym_id: Pid-v1
    num_envs: 16
    total_timesteps: 150000
  CAPS:
    gym_id: Pid-v0
    num_envs: 16
    total_timesteps: 150000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05
  FSCAPS:
    gym_id: Pid-v1
    num_envs: 16
    total_timesteps: 150000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05

Penalty:
  PURE:
    gym_id: Penalty-v0
    num_envs: 16
    total_timesteps: 150000
  FRAMESKIP:
    gym_id: Penalty-v1
    num_envs: 16
    total_timesteps: 150000
  CAPS:
    gym_id: Penalty-v0
    num_envs: 16
    total_timesteps: 150000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05
  FSCAPS:
    gym_id: Penalty-v1
    num_envs: 6
    total_timesteps: 150000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05


Attacker:
  PURE:
    gym_id: Attacker-v0
    num_envs: 16
    total_timesteps: 150000
  FRAMESKIP:
    gym_id: Attacker-v1
    num_envs: 16
    total_timesteps: 150000
  CAPS:
    gym_id: Attacker-v0
    num_envs: 16
    total_timesteps: 150000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05
  FSCAPS:
    gym_id: Attacker-v1
    num_envs: 20
    total_timesteps: 500000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05
    learning_starts: 5000
    tau: 0.999
    policy_frequency: 1
    policy_lr: 0.0001
    q_lr: 0.0001
    batch_size: 256
    gamma: 0.95

AttackerEF:
  PURE:
    gym_id: Attacker-v2
    num_envs: 16
    total_timesteps: 150000
  FRAMESKIP:
    gym_id: Attacker-v3
    num_envs: 16
    total_timesteps: 150000
  CAPS:
    gym_id: Attacker-v2
    num_envs: 16
    total_timesteps: 150000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05
  FSCAPS:
    gym_id: Attacker-v3
    num_envs: 6
    total_timesteps: 500000
    autotune: True
    lambda_temporal: 1
    lambda_spacial: 5
    caps_epsilon: 0.05
    learning_starts: 5000
    tau: 0.999
    policy_frequency: 1
    policy_lr: 0.0001
    q_lr: 0.0001
    batch_size: 256
    gamma: 0.95